server:
  ip: 47.93.8.119
  port: 9090

#172.24.99.223
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.24.99.223:3306/mu?serverTimezone=GMT%2b8
    username: root
    password: '1234'
    type: com.alibaba.druid.pool.DruidDataSource

  mail:
    #    protocol: smtps
    protocol: smtps
    # 配置 SMTP 服务器地址
    host: smtp.163.com
    # 发送者邮箱
    #    username: xqnode@163.com
    username: muyubingri@163.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: VOCBWIOYHZBDMBCL
    # 端口号465或587
    #    port: 465
    port: 465
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#mybatis:
#  mapper-locations: classpath:mapper/*.xml #?????mybatisxml??
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


files:
  upload:
#    path: E:/university/Code/system/files/
   path: /home/files/

springfox:
  documentation:
    swagger-ui:
      enabled: true